import re
with open('macron_ui_v3.py','r') as f: c=f.read()
changes=0
if 'showFinderDesktop' not in c:
    c=c.replace('        <button class="qa-btn" onclick="summarizeMail()">&#128240; Resumir Mail</button>\n    </div>','        <button class="qa-btn" onclick="summarizeMail()">&#128240; Resumir Mail</button>\n        <button class="qa-btn" onclick="showFinderDesktop()">&#128193; Desktop</button>\n        <button class="qa-btn" onclick="showFinderDownloads()">&#128229; Downloads</button>\n        <button class="qa-btn" onclick="showFinderRecent()">&#128338; Recientes</button>\n    </div>')
    changes+=1; print('+ Botones')
if '/api/finder/desktop' not in c:
    c=c.replace("@app.route('/api/mail/search', methods=['POST'])\ndef mail_search():\n    try:\n        data = request.get_json()\n        query = data.get('query', '')\n        limit = data.get('limit', 10)\n        core = get_macron_core()\n        results = core.mail_search(query, limit)\n        return jsonify({'results': results, 'count': len(results)})\n    except Exception as e:\n        return jsonify({'error': str(e)}), 500\n\nif __name__ == '__main__':","@app.route('/api/mail/search', methods=['POST'])\ndef mail_search():\n    try:\n        data = request.get_json()\n        query = data.get('query', '')\n        limit = data.get('limit', 10)\n        core = get_macron_core()\n        results = core.mail_search(query, limit)\n        return jsonify({'results': results, 'count': len(results)})\n    except Exception as e:\n        return jsonify({'error': str(e)}), 500\n\n@app.route('/api/finder/desktop')\ndef finder_desktop():\n    try:\n        core = get_macron_core()\n        files = core.finder_desktop()\n        return jsonify({'files': files, 'count': len(files)})\n    except Exception as e:\n        return jsonify({'error': str(e), 'files': []}), 500\n\n@app.route('/api/finder/downloads')\ndef finder_downloads():\n    try:\n        core = get_macron_core()\n        files = core.finder_downloads()\n        return jsonify({'files': files, 'count': len(files)})\n    except Exception as e:\n        return jsonify({'error': str(e), 'files': []}), 500\n\n@app.route('/api/finder/recent')\ndef finder_recent():\n    try:\n        core = get_macron_core()\n        limit = request.args.get('limit', 10, type=int)\n        files = core.finder_recent(limit)\n        return jsonify({'files': files, 'count': len(files)})\n    except Exception as e:\n        return jsonify({'error': str(e), 'files': []}), 500\n\n@app.route('/api/finder/search', methods=['POST'])\ndef finder_search():\n    try:\n        data = request.get_json()\n        query = data.get('query', '')\n        limit = data.get('limit', 20)\n        core = get_macron_core()\n        results = core.finder_search(query, limit)\n        return jsonify({'results': results, 'count': len(results)})\n    except Exception as e:\n        return jsonify({'error': str(e)}), 500\n\nif __name__ == '__main__':")
    changes+=1; print('+ Endpoints')
if 'async function showFinderDesktop' not in c:
    c=c.rstrip()[:-len('refreshStatus();')]+"async function showFinderDesktop() {\n    try {\n        const response = await fetch('/api/finder/desktop');\n        const data = await response.json();\n        console.log('[DEBUG] Desktop:', data);\n        let text = '--- Desktop (' + data.count + ' archivos):\\n\\n';\n        if (data.files && data.files.length) {\n            data.files.slice(0, 10).forEach(f => {\n                const icon = f.is_dir ? '>>' : '>';\n                text += icon + ' ' + f.name + '\\n';\n            });\n            if (data.files.length > 10) text += '\\n... y ' + (data.files.length - 10) + ' mas';\n        } else {\n            text += 'Desktop vacio.';\n        }\n        addMessage(text, false);\n    } catch (e) {\n        console.error('[DEBUG] Finder error:', e);\n        addMessage('Error accediendo a Desktop', false, true);\n    }\n}\n\nasync function showFinderDownloads() {\n    try {\n        const response = await fetch('/api/finder/downloads');\n        const data = await response.json();\n        console.log('[DEBUG] Downloads:', data);\n        let text = '--- Downloads (' + data.count + ' archivos):\\n\\n';\n        if (data.files && data.files.length) {\n            data.files.slice(0, 10).forEach(f => {\n                const icon = f.is_dir ? '>>' : '>';\n                text += icon + ' ' + f.name + '\\n';\n            });\n            if (data.files.length > 10) text += '\\n... y ' + (data.files.length - 10) + ' mas';\n        } else {\n            text += 'Downloads vacio.';\n        }\n        addMessage(text, false);\n    } catch (e) {\n        console.error('[DEBUG] Finder error:', e);\n        addMessage('Error accediendo a Downloads', false, true);\n    }\n}\n\nasync function showFinderRecent() {\n    try {\n        const response = await fetch('/api/finder/recent?limit=10');\n        const data = await response.json();\n        console.log('[DEBUG] Recent:', data);\n        let text = '--- Recientes (' + data.count + '):\\n\\n';\n        if (data.files && data.files.length) {\n            data.files.forEach(f => {\n                text += '> ' + f.name + '\\n';\n            });\n        } else {\n            text += 'No hay archivos recientes.';\n        }\n        addMessage(text, false);\n    } catch (e) {\n        console.error('[DEBUG] Finder error:', e);\n        addMessage('Error accediendo a recientes', false, true);\n    }\n}\n\nrefreshStatus();"
    changes+=1; print('+ JS')
with open('macron_ui_v3.py','w') as f: f.write(c)
print('Cambios: %d' % changes)
